config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :users
  mount Avo::Engine, at: Avo.configuration.root_path
  resources :articles do
    resources :comments
  end
  resources :tags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'articles#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  body       :text
#  status     :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Article < ApplicationRecord
    include Visible

    has_many :comments, dependent: :destroy
    has_many :article_tags, dependent: :destroy
    has_many :tags, through: :article_tags

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/article_tag.rb
# == Schema Information
#
# Table name: article_tags
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :integer          not null
#  tag_id     :integer          not null
#
# Indexes
#
#  index_article_tags_on_article_id  (article_id)
#  index_article_tags_on_tag_id      (tag_id)
#
# Foreign Keys
#
#  article_id  (article_id => articles.id)
#  tag_id      (tag_id => tags.id)
#
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  commenter  :string
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :integer          not null
#
# Indexes
#
#  index_comments_on_article_id  (article_id)
#
# Foreign Keys
#
#  article_id  (article_id => articles.id)
#
class Comment < ApplicationRecord
include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
    has_many :article_tags, dependent: :destroy
    has_many :articles, through: :article_tags
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article) .permit(:title, :body, :status, tag_ids: [])
    end
end

app/controllers/avo/users_controller.rb
# This controller has been generated to enable Rails' resource routes.
# You shouldn't need to modify it in order to use Avo.
class Avo::UsersController < Avo::ResourcesController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tag = Tag.new
        @tags = Tag.all
    end

    def show
        @tag = Tag.find(params[:id])
    end

    def create 
        @tag = Tag.create(tag_params)
        respond_to do |format|
            format.html {redirect_to tags_url}
            format.js
        end
    end

    private
        def tag_params
            params.require(:tag).permit(:name)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <br>

    <div>
        <%= form.label :tags %>
        <%= form.select :tag_ids, options_from_collection_for_select(Tag.all, 'id', 'name'), {}, { multiple: true } %>
    </div>

    <br>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %><br>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <br>

    <div>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

    <br>
    
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<br>
<br>

The first bullet points are the titles of the articles. The bullet
points underneath are the tags that the articles have. Clicking on 
the article title will bring you to the article. Clicking on a tag will
bring you to a page where you can see all the articles with that same
tag.

<br>

<ul>
    <% @articles.each do |article| %>
        <% unless article.archived? %>
            <li>
                <%= link_to article.title, article %>
            </li>
            <ul>
            <% if article.tags.any? %>
                <% article.tags.each do |tag| %>
                    <li>
                        <%= link_to tag.name, tag %>
                    </li>
                <% end %>
            <% end %>
            
    <% end %>
</ul>

<% end %>
</ul>

<br>
<br>

<%= link_to "New Article", new_article_path %>

<br>
<br>

<%= link_to "View Tags/Create New Tag", tags_url %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
    <div>
        <%= form.lable :title %><br>
        <%= form.text_field :title %>
        <% @article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <% @article.errors...full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Destroy", article_path(@article), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<br>

<%= link_to "Back to Articles", articles_url %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %> 
   <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <p>
        <%= link_to "Destroy Comment", [comment.article, comment], data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/tags/_form.html.erb
<%= form_for @tag, remote: true do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<ul>
    <% @tags.each do |tag| %>
        <li><%= link_to tag.name, tag %></li>
    <% end %>
</ul>

<div>
    <h1>New Tag</h1>
    <%= render 'form' %>
</div>

<br>
<br>

<%= link_to "All Articles", articles_url %>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<h1><%= "#{@tag.name} Articles" %></h1>

<ul>
    <% @tag.articles.each do |article| %>
        <li><%= link_to article.title, article %></li>
    <% end %>
</ul>

<br>
<br>

<%= link_to "All Articles", articles_url %>

<br>
<br>

<%= link_to "All Tags", tags_url %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>